type: "orchestration"
version: "1.0"
pipeline:
  components:
    Data Ingestion Start:
      type: "start"
      transitions:
        unconditional:
        - "Initialize File Registry"
      parameters:
        componentName: "Data Ingestion Start"
    Initialize File Registry:
      type: "run-transformation"
      transitions:
        success:
        - "File Processing Iterator"
      parameters:
        componentName: "Initialize File Registry"
        transformationJob: "PROJECT_RESTURANT/FILE_TABLE_NAME_CREATOR.tran.yaml"
        setScalarVariables:
        setGridVariables:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    File Processing Iterator:
      type: "table-iterator"
      transitions:
        success:
        - "Ingestion Completion Logger"
      iterationTarget: "Dynamic Table Creator"
      parameters:
        componentName: "File Processing Iterator"
        mode: "Basic"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "file_list"
        concurrency: "Sequential"
        columnMapping:
        - - "file_name"
          - "file_name"
        - - "table_name"
          - "table_name"
        orderBy:
        sort: "Ascending"
        breakOnFailure: "No"
    Dynamic Table Creator:
      type: "sql-executor"
      parameters:
        componentName: "Dynamic Table Creator"
        scriptLocation: "Component"
        declareSqlVariables: "Include all"
        sqlScript: "-- Restaurant Data Ingestion Pipeline\n-- Automated table creation\
          \ and data loading for: ${file_name}\n\n-- Step 1: Create table with inferred\
          \ schema\nCREATE OR REPLACE TABLE ${table_name}\nUSING TEMPLATE (\n  SELECT\
          \ ARRAY_AGG(OBJECT_CONSTRUCT(*))\n  FROM TABLE(\n    INFER_SCHEMA(\n   \
          \   LOCATION => '@${stage_name}/${file_name}',\n      FILE_FORMAT => '${file_format}'\n\
          \    )\n  )\n);\n\n-- Step 2: Add table comment with metadata\nALTER TABLE\
          \ ${table_name} SET COMMENT = 'Restaurant data table for ${file_name} -\
          \ Auto-generated';\n\n-- Step 3: Load data with comprehensive error handling\n\
          COPY INTO ${table_name}\nFROM '@${stage_name}/${file_name}'\nFILE_FORMAT\
          \ = (\n  TYPE = 'CSV' \n  SKIP_HEADER = 1 \n  FIELD_OPTIONALLY_ENCLOSED_BY\
          \ = '\"'\n  TRIM_SPACE = TRUE\n  ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE\n\
          )\nON_ERROR = 'CONTINUE'\nPURGE = FALSE;\n"
      postProcessing:
        updateOutputMessage: "✅ Successfully processed ${file_name} → ${table_name}\
          \ table created"
        updateScalarVariables:
    Ingestion Completion Logger:
      type: "sql-executor"
      transitions:
        success:
        - "Restaurant Analytics Pipeline"
      parameters:
        componentName: "Ingestion Completion Logger"
        scriptLocation: "Component"
        declareSqlVariables: "Include all"
        sqlScript: |
          -- Restaurant Data Ingestion Summary
          -- Create audit log and completion tracking

          -- Create ingestion log table if not exists
          CREATE TABLE IF NOT EXISTS restaurant_ingestion_log (
            pipeline_run_id VARCHAR(50) PRIMARY KEY,
            total_files_processed INTEGER,
            completion_timestamp TIMESTAMP,
            status VARCHAR(20),
            pipeline_version VARCHAR(10)
          );

          -- Log successful completion
          INSERT INTO restaurant_ingestion_log (
            pipeline_run_id,
            total_files_processed,
            completion_timestamp,
            status,
            pipeline_version
          )
          VALUES (
            'PIPELINE_' || TO_VARCHAR(CURRENT_TIMESTAMP(), 'YYYYMMDD_HH24MISS'),
            4,
            CURRENT_TIMESTAMP(),
            'SUCCESS',
            '1.0'
          );
      postProcessing:
        updateOutputMessage: "🎯 Data ingestion completed successfully - 4 restaurant\
          \ tables created and ready for analytics"
        updateScalarVariables:
    Restaurant Analytics Pipeline:
      type: "run-transformation"
      transitions:
        success:
        - "Executive Dashboard Pipeline"
      parameters:
        componentName: "Restaurant Analytics Pipeline"
        transformationJob: "PROJECT_RESTURANT/trnx_resturant.tran.yaml"
        setScalarVariables:
        setGridVariables:
      postProcessing:
        updateOutputMessage: "📊 Business analytics completed - CLV, AOV, and performance\
          \ metrics generated for strategic insights"
        updateScalarVariables:
    Executive Dashboard Pipeline:
      type: "run-transformation"
      parameters:
        componentName: "Executive Dashboard Pipeline"
        transformationJob: "PROJECT_RESTURANT/executive_dashboard.tran.yaml"
        setScalarVariables:
        setGridVariables:
      postProcessing:
        updateOutputMessage: "💼 Executive dashboards ready - Real-time KPIs operational\
          \ with $130K revenue opportunities identified"
        updateScalarVariables:
  variables:
    file_name:
      metadata:
        type: "TEXT"
        description: "Current file being processed from restaurant data stage"
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    stage_name:
      metadata:
        type: "TEXT"
        description: "Snowflake stage containing restaurant CSV files"
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "mat_pro.resturant"
    table_name:
      metadata:
        type: "TEXT"
        description: "Target table name for current file processing"
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    file_format:
      metadata:
        type: "TEXT"
        description: "File format definition for CSV parsing"
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "mat_pro.infer_fmt"
design:
  components:
    Data Ingestion Start:
      position:
        x: 0
        "y": 0
      tempMetlId: 1
    Initialize File Registry:
      position:
        x: 190
        "y": 0
      tempMetlId: 2
    File Processing Iterator:
      position:
        x: 470
        "y": -20
      tempMetlId: 3
    Dynamic Table Creator:
      position:
        x: 470
        "y": -20
      tempMetlId: 4
    Ingestion Completion Logger:
      position:
        x: 780
        "y": 0
      tempMetlId: 5
    Restaurant Analytics Pipeline:
      position:
        x: 1120
        "y": 0
      tempMetlId: 6
    Executive Dashboard Pipeline:
      position:
        x: 1490
        "y": 0
      tempMetlId: 7
  notes:
    "1":
      position:
        x: -200
        "y": -340
      size:
        height: 525
        width: 320
      theme: "light-blue"
      content: "### **🚀 Data Ingestion Pipeline**\n\n**Purpose:** Professional restaurant\
        \ data loading system\n\n**Source Files:**\n- 🍽️ Menu Items (`rest_menus.csv`)\n\
        - 📋 Orders (`rest_orders.csv`) \n- 👤 Customers (`rest_customers.csv`)\n\
        - 👥 Employees (`rest_employees.csv`)\n\n**Features:**\n- Automated schema\
        \ inference\n- Error handling and logging\n- Data quality validation\n- Audit\
        \ trail creation\n"
    "2":
      position:
        x: 290
        "y": -350
      size:
        height: 535
        width: 320
      theme: "light-green"
      content: |
        ### **⚙️ Processing Engine**

        **Advanced Capabilities:**
        - Dynamic table creation
        - Parallel file processing
        - Comprehensive error handling
        - Real-time status monitoring
        - Quality assurance checks
    "3":
      position:
        x: 670
        "y": -350
      size:
        height: 525
        width: 280
      theme: "green"
      content: |-
        ### **📊 Data Validation & Logging**

        **Quality Assurance:**
        - Record count verification
        - Load timestamp tracking
        - Success/failure logging
        - Pipeline completion status
        - Audit trail maintenance
        - Performance monitoring
    "4":
      position:
        x: 1020
        "y": -350
      size:
        height: 520
        width: 300
      theme: "yellow"
      content: "### **📊 Business Intelligence**\n\n**Analytics Processing:**\n- Customer\
        \ Lifetime Value (CLV)\n- Average Order Value (AOV) \n- Employee performance\
        \ metrics\n- Menu item rankings\n- Customer retention analysis\n"
    "5":
      position:
        x: 1380
        "y": -350
      size:
        height: 505
        width: 320
      theme: "red"
      content: "### **💼 Executive Dashboards**\n\n**C-Suite Intelligence:**\n- Real-time\
        \ KPI scorecards\n- Category performance rankings\n- Strategic alert system\
        \  \n- $130K revenue opportunities\n- Mobile dashboard access\n"
