type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Setup: Create File List Table"
      parameters:
        componentName: "Start"
    'Iterator: Processing Multiple Files':
      type: "table-iterator"
      iterationTarget: "Processing: ${table_name} Table from ${file_name}"
      parameters:
        componentName: "Iterator: Processing Multiple Files"
        mode: "Basic"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "file_list"
        concurrency: "Sequential"
        columnMapping:
        - - "file_name"
          - "file_name"
        - - "table_name"
          - "table_name"
        orderBy:
        sort: "Ascending"
        breakOnFailure: "No"
    'Processing: ${table_name} Table from ${file_name}':
      type: "sql-executor"
      parameters:
        componentName: "Processing: ${table_name} Table from ${file_name}"
        scriptLocation: "Component"
        declareSqlVariables: "Include all"
        sqlScript: |
          -- Step 1: Create table using inferred schema for file: ${file_name}
          CREATE OR REPLACE TABLE ${table_name}
          USING TEMPLATE (
            SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
            FROM TABLE(
              INFER_SCHEMA(
                LOCATION => '@${stage_name}/${file_name}',
                FILE_FORMAT =>'${file_format}'
              )
            )
          );

          -- Step 2: Load data from stage for file: ${file_name}
          COPY INTO ${table_name}
          FROM '@${stage_name}/${file_name}'
          FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1)
          ON_ERROR = 'CONTINUE';
    'Setup: Create File List Table':
      type: "run-transformation"
      transitions:
        success:
        - "Iterator: Processing Multiple Files"
      parameters:
        componentName: "Setup: Create File List Table"
        transformationJob: "PROJECT_RESTURANT/FILE_TABLE_NAME_CREATOR.tran.yaml"
        setScalarVariables:
        setGridVariables:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
  variables:
    file_name:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    stage_name:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "mat_pro.resturant"
    table_name:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    file_format:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "mat_pro.infer_fmt"
design:
  components:
    Start:
      position:
        x: 0
        "y": 0
      tempMetlId: 1
    'Iterator: Processing Multiple Files':
      position:
        x: 470
        "y": -20
      tempMetlId: 3
    'Processing: ${table_name} Table from ${file_name}':
      position:
        x: 470
        "y": -20
      tempMetlId: 4
    'Setup: Create File List Table':
      position:
        x: 210
        "y": 0
      tempMetlId: 5
