type: "transformation"
version: "1.0"
pipeline:
  components:
    REST_CUSTOMERS:
      type: "table-input"
      parameters:
        componentName: "REST_CUSTOMERS"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "REST_CUSTOMERS"
        columnNames:
        - "customer_id"
        - "customer_name"
        - "join_date"
        - "loyalty_level"
        - "age"
        - "city"
        timeOffset:
    REST_EMPLOYEES:
      type: "table-input"
      parameters:
        componentName: "REST_EMPLOYEES"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "REST_EMPLOYEES"
        columnNames:
        - "employee_id"
        - "employee_name"
        - "hire_date"
        - "position"
        timeOffset:
    REST_MENUS:
      type: "table-input"
      parameters:
        componentName: "REST_MENUS"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "REST_MENUS"
        columnNames:
        - "menu_id"
        - "item_name"
        - "category"
        - "price"
        timeOffset:
    REST_ORDER:
      type: "table-input"
      parameters:
        componentName: "REST_ORDER"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "REST_ORDER"
        columnNames:
        - "order_id"
        - "order_date"
        - "customer_id"
        - "employee_id"
        - "menu_id"
        - "quantity"
        timeOffset:
    Master Data Join:
      type: "join"
      sources:
      - "REST_CUSTOMERS"
      - "REST_EMPLOYEES"
      - "REST_MENUS"
      - "REST_ORDER"
      parameters:
        componentName: "Master Data Join"
        mainTable: "REST_CUSTOMERS"
        mainTableAlias: "c"
        joins:
        - - "REST_ORDER"
          - "o"
          - "Inner"
        - - "REST_MENUS"
          - "m"
          - "Inner"
        - - "REST_EMPLOYEES"
          - "e"
          - "Inner"
        joinExpressions:
        - - "\"c\".\"customer_id\"=\"o\".\"customer_id\""
          - "c_Inner_o"
        - - "\"o\".\"menu_id\"=\"m\".\"menu_id\""
          - "c_Inner_m"
        - - "\"o\".\"employee_id\"=\"e\".\"employee_id\""
          - "c_Inner_e"
        columnMappings:
        - - "c.customer_id"
          - "customer_id"
        - - "c.customer_name"
          - "customer_name"
        - - "c.join_date"
          - "join_date"
        - - "c.loyalty_level"
          - "loyalty_level"
        - - "c.age"
          - "age"
        - - "c.city"
          - "city"
        - - "o.order_id"
          - "order_id"
        - - "o.order_date"
          - "order_date"
        - - "m.category"
          - "category"
        - - "m.item_name"
          - "item_name"
        - - "o.quantity"
          - "quantity"
        - - "m.price"
          - "price"
        - - "m.menu_id"
          - "menu_id"
        - - "e.employee_id"
          - "employee_id"
        - - "e.employee_name"
          - "employee_name"
        - - "e.position"
          - "position"
        - - "e.hire_date"
          - "hire_date"
    Master Dataset Output:
      type: "rewrite-table"
      sources:
      - "Master Data Join"
      parameters:
        componentName: "Master Dataset Output"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "master_rest_table"
        orderBy:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Order Value Calculator:
      type: "calculator"
      sources:
      - "Master Data Join"
      parameters:
        componentName: "Order Value Calculator"
        includeInputColumns: "Yes"
        calculations:
        - - "COALESCE((\"price\"*\"quantity\"),0)"
          - "total_price"
    CLV Aggregation:
      type: "aggregate"
      sources:
      - "Order Value Calculator"
      parameters:
        componentName: "CLV Aggregation"
        groupings:
        - "customer_id"
        - "customer_name"
        aggregations:
        - - "total_price"
          - "Sum"
        groupingType: "Group By"
    Customer Lifetime Value:
      type: "rewrite-table"
      sources:
      - "Rename 3"
      parameters:
        componentName: "Customer Lifetime Value"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "CLV"
        orderBy:
        - - "customer_id"
          - "ASCENDING"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    AOV Calculation:
      type: "aggregate"
      sources:
      - "Order Value Calculator"
      parameters:
        componentName: "AOV Calculation"
        groupings:
        aggregations:
        - - "total_price"
          - "Average"
        groupingType: "Group By"
    ' Average Order Value':
      type: "rewrite-table"
      sources:
      - "Rename"
      parameters:
        componentName: " Average Order Value"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "AOV"
        orderBy:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Menu Performance Analysis:
      type: "aggregate"
      sources:
      - "Order Value Calculator"
      parameters:
        componentName: "Menu Performance Analysis"
        groupings:
        - "item_name"
        - "category"
        aggregations:
        - - "quantity"
          - "Sum"
        - - "total_price"
          - "Sum"
        groupingType: "Group By"
    AOV Column Formatting:
      type: "rename"
      sources:
      - "AOV Calculation"
      parameters:
        componentName: "AOV Column Formatting"
        columnMapping:
        - - "avg_total_price"
          - "avg_order_value"
        includeInputColumns: "No"
    Rename 2:
      type: "rename"
      sources:
      - "Top Selling Menu Items"
      parameters:
        componentName: "Rename 2"
        columnMapping:
        - - "item_name"
          - "item_name"
        - - "category"
          - "category"
        - - "sum_quantity"
          - "total_quantity_sold"
        - - "sum_total_price"
          - "total_revenue"
        includeInputColumns: "No"
    Rename 3:
      type: "rename"
      sources:
      - "Total revenue generated per customer over time"
      parameters:
        componentName: "Rename 3"
        columnMapping:
        - - "sum_total_price"
          - "total_spent"
        - - "customer_id"
          - "customer_id"
        - - "customer_name"
          - "customer_name"
        includeInputColumns: "No"
    Top Selling Menu Items (by Revenue & Quantity):
      type: "rewrite-table"
      sources:
      - "Rename 2"
      parameters:
        componentName: "Top Selling Menu Items (by Revenue & Quantity)"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "TOP_SELLING"
        orderBy:
        - - "total_revenue"
          - "DESCENDING"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Employee Performance Analysis:
      type: "aggregate"
      sources:
      - "Order Value Calculator"
      parameters:
        componentName: "Employee Performance Analysis"
        groupings:
        - "employee_name"
        - "position"
        aggregations:
        - - "customer_id"
          - "Count"
        - - "total_price"
          - "Sum"
        groupingType: "Group By"
    Rename 4:
      type: "rename"
      sources:
      - " employees generate the most revenue"
      parameters:
        componentName: "Rename 4"
        columnMapping:
        - - "employee_name"
          - "employee_name"
        - - "position"
          - "position"
        - - "count_customer_id"
          - "total_orders_handled"
        - - "sum_total_price"
          - "total_revenue_generated"
        includeInputColumns: "No"
    ' Employee Sales Performance':
      type: "rewrite-table"
      sources:
      - "Rename 4"
      parameters:
        componentName: " Employee Sales Performance"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "SALES_PERFO"
        orderBy:
        - - "total_revenue_generated"
          - "DESCENDING"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Customer Order Join:
      type: "join"
      sources:
      - "REST_CUSTOMERS"
      - "REST_ORDER"
      parameters:
        componentName: "Customer Order Join"
        mainTable: "REST_CUSTOMERS"
        mainTableAlias: "c"
        joins:
        - - "REST_ORDER"
          - "o"
          - "Left"
        joinExpressions:
        - - "\"c\".\"customer_id\"=\"o\".\"customer_id\""
          - "c_Left_o"
        columnMappings:
        - - "c.customer_id"
          - "customer_id"
        - - "c.loyalty_level"
          - "loyalty_level"
        - - "o.order_id"
          - "order_id"
    Customer Retention by Loyalty:
      type: "aggregate"
      sources:
      - "Customer Order Join"
      parameters:
        componentName: "Customer Retention by Loyalty"
        groupings:
        - "loyalty_level"
        aggregations:
        - - "customer_id"
          - "Count Distinct"
        groupingType: "Group By"
    Returning Customers by Loyalty:
      type: "filter"
      sources:
      - "Customer Order Join"
      parameters:
        componentName: "Returning Customers by Loyalty"
        filterConditions:
        - - "order_id"
          - "Not"
          - "Null"
          - ""
        combineCondition: "And"
    Returning Customer Count:
      type: "aggregate"
      sources:
      - "Returning Customers by Loyalty"
      parameters:
        componentName: "Returning Customer Count"
        groupings:
        - "loyalty_level"
        aggregations:
        - - "customer_id"
          - "Count Distinct"
        groupingType: "Group By"
    Retention Rate Calculation:
      type: "join"
      sources:
      - "Customer Retention by Loyalty"
      - "Returning Customer Count"
      parameters:
        componentName: "Retention Rate Calculation"
        mainTable: "Customer Retention by Loyalty"
        mainTableAlias: "total"
        joins:
        - - "Returning Customer Count"
          - "returning"
          - "Left"
        joinExpressions:
        - - "\"total\".\"loyalty_level\"=\"returning\".\"loyalty_level\""
          - "total_Left_returning"
        columnMappings:
        - - "total.loyalty_level"
          - "loyalty_level"
        - - "total.count_distinct_customer_id"
          - "total_customers"
        - - "returning.count_distinct_customer_id"
          - "returning_customers"
    Customer Retention Results:
      type: "calculator"
      sources:
      - "Retention Rate Calculation"
      parameters:
        componentName: "Customer Retention Results"
        includeInputColumns: "Yes"
        calculations:
        - - |
            COALESCE("returning_customers", 0)
          - "returning_customers_fixed"
        - - "ROUND(\n    COALESCE(\"returning_customers\", 0) * 100.0 / \n    NULLIF(\"\
            total_customers\", 0), 2\n)\n"
          - "retention_rate_percent"
    Customer Retention Analysis Results:
      type: "rewrite-table"
      sources:
      - "Customer Retention Results"
      parameters:
        componentName: "Customer Retention Analysis Results"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "CUSTOMER_RETENTION"
        orderBy:
        - - "retention_rate_percent"
          - "DESCENDING"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
design:
  components:
    REST_CUSTOMERS:
      position:
        x: 0
        "y": 360
      tempMetlId: 1
    REST_EMPLOYEES:
      position:
        x: 0
        "y": 440
      tempMetlId: 2
    REST_MENUS:
      position:
        x: 0
        "y": 520
      tempMetlId: 3
    REST_ORDER:
      position:
        x: 0
        "y": 600
      tempMetlId: 4
    Master Data Join:
      position:
        x: 280
        "y": 480
      tempMetlId: 5
    Master Dataset Output:
      position:
        x: 1200
        "y": 480
      tempMetlId: 6
    Order Value Calculator:
      position:
        x: 460
        "y": 480
      tempMetlId: 7
    CLV Aggregation:
      position:
        x: 640
        "y": 80
      tempMetlId: 8
    Customer Lifetime Value:
      position:
        x: 1000
        "y": 80
      tempMetlId: 9
    AOV Calculation:
      position:
        x: 640
        "y": 440
      tempMetlId: 10
    ' Average Order Value':
      position:
        x: 1000
        "y": 440
      tempMetlId: 11
    Menu Performance Analysis:
      position:
        x: 640
        "y": 920
      tempMetlId: 12
    AOV Column Formatting:
      position:
        x: 920
        "y": 440
      tempMetlId: 13
    Rename 2:
      position:
        x: 820
        "y": 920
      tempMetlId: 14
    Rename 3:
      position:
        x: 820
        "y": 80
      tempMetlId: 15
    Top Selling Menu Items (by Revenue & Quantity):
      position:
        x: 1000
        "y": 920
      tempMetlId: 16
    Employee Performance Analysis:
      position:
        x: 640
        "y": 1160
      tempMetlId: 17
    Rename 4:
      position:
        x: 820
        "y": 1160
      tempMetlId: 18
    ' Employee Sales Performance':
      position:
        x: 1000
        "y": 1160
      tempMetlId: 19
    Customer Order Join:
      position:
        x: 280
        "y": 1320
      tempMetlId: 20
    Customer Retention by Loyalty:
      position:
        x: 460
        "y": 1320
      tempMetlId: 21
    Returning Customers by Loyalty:
      position:
        x: 460
        "y": 1440
      tempMetlId: 22
    Returning Customer Count:
      position:
        x: 640
        "y": 1440
      tempMetlId: 23
    Retention Rate Calculation:
      position:
        x: 820
        "y": 1360
      tempMetlId: 24
    Customer Retention Results:
      position:
        x: 1000
        "y": 1360
      tempMetlId: 25
    Customer Retention Analysis Results:
      position:
        x: 1200
        "y": 1360
      tempMetlId: 26
  notes:
    "1":
      position:
        x: 76
        "y": 65
      size:
        height: 280
        width: 220
      theme: "light-blue"
      content: |
        ### **📊 Source Data**
        
        **Restaurant Tables:**
        - 🧑 Customers (loyalty levels)
        - 👥 Employees (positions)
        - 🍽️ Menu Items (categories)
        - 📋 Orders (transactions)
    "2":
      position:
        x: 318
        "y": 75
      size:
        height: 250
        width: 280
      theme: "light-green"
      content: |
        ### **🔗 Data Processing**
        
        **Core Operations:**
        - Joins all 4 tables
        - Calculates total_price (price × quantity)
        - Creates master dataset
        - Feeds all KPI branches
    "3":
      position:
        x: 580
        "y": -121
      size:
        height: 175
        width: 480
      theme: "light-yellow"
      content: |
        ### **💰 KPI #1: Customer Lifetime Value**
        
        **Question:** Who are most valuable customers?
        **Output:** CLV table with rankings
    "4":
      position:
        x: 618
        "y": 301
      size:
        height: 115
        width: 480
      theme: "light-yellow"
      content: |
        ### **📈 KPI #2: Average Order Value**
        
        **Question:** Average transaction size?
    "5":
      position:
        x: 139
        "y": 580
      size:
        height: 100
        width: 480
      theme: "light-yellow"
      content: |
        ### **🍔 KPI #3: Top Selling Items**
        
        **Output:** TOP_SELLING table
    "6":
      position:
        x: 780
        "y": 739
      size:
        height: 160
        width: 480
      theme: "light-yellow"
      content: |
        ### **👥 KPI #4: Employee Performance**
        
        **Question:** Top performing employees?
        **Output:** SALES_PERFO table
    "7":
      position:
        x: -421
        "y": 780
      size:
        height: 115
        width: 1040
      theme: "red"
      content: |
        ### **🎯 KPI #5: Customer Retention by Loyalty Level**
        
        **Method:** LEFT join captures ALL customers | **Output:** CUSTOMER_RETENTION
    "8":
      position:
        x: 1180
        "y": 0
      size:
        height: 330
        width: 200
      theme: "green"
      content: |
        ### **📤 Final Tables**
        
        **6 Analytics Outputs:**
        
        ✅ Master Dataset
        ✅ CLV
        ✅ AOV
        ✅ TOP_SELLING
        ✅ SALES_PERFO
        ✅ RETENTION
        
        **Dashboard Ready!** 📊
