type: "transformation"
version: "1.0"
pipeline:
  components:
    REST_CUSTOMERS:
      type: "table-input"
      parameters:
        componentName: "REST_CUSTOMERS"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "REST_CUSTOMERS"
        columnNames:
        - "customer_id"
        - "customer_name"
        - "join_date"
        - "loyalty_level"
        - "age"
        - "city"
        timeOffset:
      postProcessing:
        updateOutputMessage: "📊 REST_CUSTOMERS table loaded for analytics"
        updateScalarVariables:
    REST_ORDER:
      type: "table-input"
      parameters:
        componentName: "REST_ORDER"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "REST_ORDER"
        columnNames:
        - "order_id"
        - "order_date"
        - "customer_id"
        - "employee_id"
        - "menu_id"
        - "quantity"
        timeOffset:
      postProcessing:
        updateOutputMessage: "📊 REST_ORDER table loaded for analytics"
        updateScalarVariables:
    REST_MENUS:
      type: "table-input"
      parameters:
        componentName: "REST_MENUS"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "REST_MENUS"
        columnNames:
        - "menu_id"
        - "item_name"
        - "category"
        - "price"
        timeOffset:
      postProcessing:
        updateOutputMessage: "🍽️ REST_MENUS table loaded for analytics"
        updateScalarVariables:
    Master Data Join:
      type: "join"
      sources:
      - "REST_ORDER"
      - "REST_MENUS"
      - "REST_CUSTOMERS"
      parameters:
        componentName: "Master Data Join"
        mainTable: "REST_ORDER"
        mainTableAlias: "o"
        joins:
        - - "REST_CUSTOMERS"
          - "c"
          - "Inner"
        - - "REST_MENUS"
          - "m"
          - "Inner"
        joinExpressions:
        - - "\"o\".\"customer_id\"=\"c\".\"customer_id\""
          - "o_Inner_c"
        - - "\"o\".\"menu_id\"=\"m\".\"menu_id\""
          - "o_Inner_m"
        columnMappings:
        - - "c.customer_id"
          - "customer_id"
        - - "c.customer_name"
          - "customer_name"
        - - "c.loyalty_level"
          - "loyalty_level"
        - - "o.order_id"
          - "order_id"
        - - "o.order_date"
          - "order_date"
        - - "m.category"
          - "category"
        - - "m.item_name"
          - "item_name"
        - - "o.quantity"
          - "quantity"
        - - "m.price"
          - "price"
      postProcessing:
        updateOutputMessage: "🔗 Master data joined successfully"
        updateScalarVariables:
    Order Value Calculator:
      type: "calculator"
      sources:
      - "Master Data Join"
      parameters:
        componentName: "Order Value Calculator"
        includeInputColumns: "Yes"
        calculations:
        - - "CASE \n  WHEN \"price\" IS NULL OR \"quantity\" IS NULL THEN 0\n  WHEN\
            \ \"price\" < 0 OR \"quantity\" < 0 THEN 0\n  ELSE COALESCE((\"price\"\
            \ * \"quantity\"), 0)\nEND\n"
          - "total_price"
      postProcessing:
        updateOutputMessage: "🧮 Order values calculated"
        updateScalarVariables:
    CLV Aggregation:
      type: "aggregate"
      sources:
      - "Order Value Calculator"
      parameters:
        componentName: "CLV Aggregation"
        groupings:
        - "customer_id"
        - "customer_name"
        aggregations:
        - - "total_price"
          - "Sum"
        groupingType: "Group By"
      postProcessing:
        updateOutputMessage: "💰 Customer Lifetime Value calculated"
        updateScalarVariables:
    Customer Lifetime Value Output:
      type: "rewrite-table"
      sources:
      - "CLV Aggregation"
      parameters:
        componentName: "Customer Lifetime Value Output"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "CLV"
        orderBy:
        - - "sum_total_price"
          - "DESCENDING"
      postProcessing:
        updateOutputMessage: "💰 Customer Lifetime Value analysis completed"
        updateScalarVariables:
    REST_EMPLOYEES:
      type: "table-input"
      parameters:
        componentName: "REST_EMPLOYEES"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "REST_EMPLOYEES"
        columnNames:
        - "employee_id"
        - "employee_name"
        - "hire_date"
        - "position"
        timeOffset:
      postProcessing:
        updateOutputMessage: "👥 REST_EMPLOYEES table loaded for analytics"
        updateScalarVariables:
    Enhanced Master Join:
      type: "join"
      sources:
      - "REST_ORDER"
      - "REST_MENUS"
      - "REST_CUSTOMERS"
      - "REST_EMPLOYEES"
      parameters:
        componentName: "Enhanced Master Join"
        mainTable: "REST_ORDER"
        mainTableAlias: "o"
        joins:
        - - "REST_CUSTOMERS"
          - "c"
          - "Inner"
        - - "REST_MENUS"
          - "m"
          - "Inner"
        - - "REST_EMPLOYEES"
          - "e"
          - "Left"
        joinExpressions:
        - - "\"o\".\"customer_id\"=\"c\".\"customer_id\""
          - "o_Inner_c"
        - - "\"o\".\"menu_id\"=\"m\".\"menu_id\""
          - "o_Inner_m"
        - - "\"o\".\"employee_id\"=\"e\".\"employee_id\""
          - "o_Left_e"
        columnMappings:
        - - "c.customer_id"
          - "customer_id"
        - - "c.customer_name"
          - "customer_name"
        - - "c.loyalty_level"
          - "loyalty_level"
        - - "c.age"
          - "age"
        - - "c.city"
          - "city"
        - - "o.order_id"
          - "order_id"
        - - "o.order_date"
          - "order_date"
        - - "m.category"
          - "category"
        - - "m.item_name"
          - "item_name"
        - - "o.quantity"
          - "quantity"
        - - "m.price"
          - "price"
        - - "e.employee_name"
          - "employee_name"
        - - "e.position"
          - "position"
      postProcessing:
        updateOutputMessage: "🔗 Enhanced master join with employees completed"
        updateScalarVariables:
    Enhanced Order Calculator:
      type: "calculator"
      sources:
      - "Enhanced Master Join"
      parameters:
        componentName: "Enhanced Order Calculator"
        includeInputColumns: "Yes"
        calculations:
        - - "CASE \n  WHEN \"price\" IS NULL OR \"quantity\" IS NULL THEN 0\n  WHEN\
            \ \"price\" < 0 OR \"quantity\" < 0 THEN 0\n  ELSE COALESCE((\"price\"\
            \ * \"quantity\"), 0)\nEND"
          - "total_price"
        - - |-
            CASE
              WHEN "total_price" > 100 THEN 'HIGH_VALUE'
              WHEN "total_price" > 30 THEN 'MEDIUM_VALUE'
              WHEN "total_price" > 0 THEN 'LOW_VALUE'
              ELSE 'NO_VALUE'
            END
          - "order_value_tier"
      postProcessing:
        updateOutputMessage: "🧮 Enhanced order calculations completed"
        updateScalarVariables:
    Master Dataset Output:
      type: "rewrite-table"
      sources:
      - "Enhanced Order Calculator"
      parameters:
        componentName: "Master Dataset Output"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "master_rest_table"
        orderBy:
      postProcessing:
        updateOutputMessage: "✅ Master dataset saved successfully"
        updateScalarVariables:
    AOV Calculation:
      type: "aggregate"
      sources:
      - "Enhanced Order Calculator"
      parameters:
        componentName: "AOV Calculation"
        groupings:
        aggregations:
        - - "total_price"
          - "Average"
        groupingType: "Group By"
      postProcessing:
        updateOutputMessage: "📈 Average Order Value calculated"
        updateScalarVariables:
    Average Order Value Output:
      type: "rewrite-table"
      sources:
      - "AOV Calculation"
      parameters:
        componentName: "Average Order Value Output"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "AOV"
        orderBy:
      postProcessing:
        updateOutputMessage: "📈 AOV analysis completed"
        updateScalarVariables:
    Menu Performance Analysis:
      type: "aggregate"
      sources:
      - "Enhanced Order Calculator"
      parameters:
        componentName: "Menu Performance Analysis"
        groupings:
        - "item_name"
        - "category"
        aggregations:
        - - "quantity"
          - "Sum"
        - - "total_price"
          - "Sum"
        groupingType: "Group By"
      postProcessing:
        updateOutputMessage: "🍔 Menu performance analyzed"
        updateScalarVariables:
    Top Selling Items Output:
      type: "rewrite-table"
      sources:
      - "Menu Performance Analysis"
      parameters:
        componentName: "Top Selling Items Output"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "TOP_SELLING"
        orderBy:
        - - "sum_total_price"
          - "DESCENDING"
      postProcessing:
        updateOutputMessage: "🍔 Top selling items saved"
        updateScalarVariables:
    Employee Performance Analysis:
      type: "aggregate"
      sources:
      - "Enhanced Order Calculator"
      parameters:
        componentName: "Employee Performance Analysis"
        groupings:
        - "employee_name"
        - "position"
        aggregations:
        - - "customer_id"
          - "Count"
        - - "total_price"
          - "Sum"
        groupingType: "Group By"
      postProcessing:
        updateOutputMessage: "👥 Employee performance calculated"
        updateScalarVariables:
    Employee Sales Performance Output:
      type: "rewrite-table"
      sources:
      - "Employee Performance Analysis"
      parameters:
        componentName: "Employee Sales Performance Output"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "SALES_PERFO"
        orderBy:
        - - "sum_total_price"
          - "DESCENDING"
      postProcessing:
        updateOutputMessage: "👥 Employee sales performance saved"
        updateScalarVariables:
    Customer Retention Analysis:
      type: "join"
      sources:
      - "REST_CUSTOMERS"
      - "REST_ORDER"
      parameters:
        componentName: "Customer Retention Analysis"
        mainTable: "REST_CUSTOMERS"
        mainTableAlias: "c"
        joins:
        - - "REST_ORDER"
          - "o"
          - "Left"
        joinExpressions:
        - - "\"c\".\"customer_id\"=\"o\".\"customer_id\""
          - "c_Left_o"
        columnMappings:
        - - "c.customer_id"
          - "customer_id"
        - - "c.loyalty_level"
          - "loyalty_level"
        - - "o.order_id"
          - "order_id"
      postProcessing:
        updateOutputMessage: "🎯 Customer retention analysis setup"
        updateScalarVariables:
    Customer Retention Calculation:
      type: "aggregate"
      sources:
      - "Customer Retention Analysis"
      parameters:
        componentName: "Customer Retention Calculation"
        groupings:
        - "loyalty_level"
        aggregations:
        - - "customer_id"
          - "Count Distinct"
        - - "order_id"
          - "Count Distinct"
        groupingType: "Group By"
      postProcessing:
        updateOutputMessage: "📊 Retention metrics calculated"
        updateScalarVariables:
    Customer Retention Formatting:
      type: "calculator"
      sources:
      - "Customer Retention Calculation"
      parameters:
        componentName: "Customer Retention Formatting"
        includeInputColumns: "Yes"
        calculations:
        - - "CASE \n  WHEN \"count_distinct_customer_id\" IS NULL OR \"count_distinct_customer_id\"\
            \ = 0 THEN 0\n  ELSE COALESCE(\"count_distinct_order_id\", 0)\nEND"
          - "returning_customers"
        - - "CASE \n  WHEN \"count_distinct_customer_id\" IS NULL OR \"count_distinct_customer_id\"\
            \ = 0 THEN 0.00\n  ELSE ROUND(COALESCE(\"count_distinct_order_id\", 0)\
            \ * 100.0 / NULLIF(\"count_distinct_customer_id\", 0), 2)\nEND"
          - "retention_rate_percent"
      postProcessing:
        updateOutputMessage: "🧮 Retention rates calculated"
        updateScalarVariables:
    Customer Retention Output:
      type: "rewrite-table"
      sources:
      - "Customer Retention Formatting"
      parameters:
        componentName: "Customer Retention Output"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "CUSTOMER_RETENTION"
        orderBy:
        - - "retention_rate_percent"
          - "DESCENDING"
      postProcessing:
        updateOutputMessage: "🎯 Customer retention analysis completed"
        updateScalarVariables:
    Seasonal Analysis:
      type: "aggregate"
      sources:
      - "Enhanced Order Calculator"
      parameters:
        componentName: "Seasonal Analysis"
        groupings:
        - "category"
        aggregations:
        - - "total_price"
          - "Sum"
        - - "quantity"
          - "Sum"
        - - "order_id"
          - "Count"
        groupingType: "Group By"
      postProcessing:
        updateOutputMessage: "🍂 Seasonal analysis completed"
        updateScalarVariables:
    Seasonal Performance Output:
      type: "rewrite-table"
      sources:
      - "Seasonal Analysis"
      parameters:
        componentName: "Seasonal Performance Output"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "SEASONAL_PERFORMANCE"
        orderBy:
        - - "sum_total_price"
          - "DESCENDING"
      postProcessing:
        updateOutputMessage: "🍂 Seasonal performance saved"
        updateScalarVariables:
design:
  components:
    REST_CUSTOMERS:
      position:
        x: 50
        "y": 50
      tempMetlId: 1
    REST_ORDER:
      position:
        x: 50
        "y": 200
      tempMetlId: 2
    REST_MENUS:
      position:
        x: 50
        "y": 350
      tempMetlId: 3
    Master Data Join:
      position:
        x: 350
        "y": 200
      tempMetlId: 4
    Order Value Calculator:
      position:
        x: 600
        "y": 200
      tempMetlId: 5
    CLV Aggregation:
      position:
        x: 850
        "y": 200
      tempMetlId: 6
    Customer Lifetime Value Output:
      position:
        x: 1030
        "y": 270
      tempMetlId: 7
    REST_EMPLOYEES:
      position:
        x: 50
        "y": 500
      tempMetlId: 8
    Enhanced Master Join:
      position:
        x: 350
        "y": 350
      tempMetlId: 9
    Enhanced Order Calculator:
      position:
        x: 600
        "y": 350
      tempMetlId: 10
    Master Dataset Output:
      position:
        x: 850
        "y": 350
      tempMetlId: 11
    AOV Calculation:
      position:
        x: 600
        "y": 500
      tempMetlId: 12
    Average Order Value Output:
      position:
        x: 850
        "y": 500
      tempMetlId: 13
    Menu Performance Analysis:
      position:
        x: 600
        "y": 650
      tempMetlId: 14
    Top Selling Items Output:
      position:
        x: 850
        "y": 650
      tempMetlId: 15
    Employee Performance Analysis:
      position:
        x: 600
        "y": 800
      tempMetlId: 16
    Employee Sales Performance Output:
      position:
        x: 850
        "y": 800
      tempMetlId: 17
    Customer Retention Analysis:
      position:
        x: 1150
        "y": 200
      tempMetlId: 18
    Customer Retention Calculation:
      position:
        x: 1400
        "y": 200
      tempMetlId: 19
    Customer Retention Formatting:
      position:
        x: 1650
        "y": 200
      tempMetlId: 20
    Customer Retention Output:
      position:
        x: 1900
        "y": 200
      tempMetlId: 21
    Seasonal Analysis:
      position:
        x: 1150
        "y": 350
      tempMetlId: 22
    Seasonal Performance Output:
      position:
        x: 1400
        "y": 350
      tempMetlId: 23
