type: "transformation"
version: "1.0"
pipeline:
  components:
    Load_Customer_Data:
      type: "table-input"
      parameters:
        componentName: "Load_Customer_Data"
        database: "[Environment Default]"
        schema: "MAT_PRO"
        targetTable: "GW_CUSTOMER_ACCOUNTS"
        columnNames:
        - "DATA_VALUE"
        timeOffset:
    Extract_Customer_Details:
      type: "extract-nested-data-sf"
      sources:
      - "Load_Customer_Data"
      parameters:
        componentName: "Extract_Customer_Details"
        includeInputColumns: "No"
        columns:
        - name: "data"
          datatype: "VARIANT"
          size: "0"
          decimalPlaces: "0"
          columnName: "DATA_VALUE"
          aliasName: "data"
          isArray: "true"
          include: "false"
          childElements:
          - name: "data-element"
            datatype: "VARIANT"
            size: "0"
            decimalPlaces: "0"
            columnName: "DATA_VALUE"
            aliasName: "data-element"
            isArray: "false"
            include: "false"
            childElements:
            - name: "customer_rid"
              datatype: "NUMBER"
              size: "0"
              decimalPlaces: "0"
              columnName: "DATA_VALUE"
              aliasName: "customer_rid"
              isArray: "false"
              include: "true"
            - name: "account_name"
              datatype: "VARCHAR"
              size: "0"
              decimalPlaces: "0"
              columnName: "DATA_VALUE"
              aliasName: "account_name"
              isArray: "false"
              include: "true"
        outerJoin: "No"
        inputAlias: "i"
        arrayPrefix: "f"
        castingMethod: "Fail on invalid data"
        caseColumnAliasNames: "No"
    Load_Items_Data:
      type: "table-input"
      parameters:
        componentName: "Load_Items_Data"
        database: "[Environment Default]"
        schema: "MAT_PRO"
        targetTable: "GW_ITEMS"
        columnNames:
        - "RowId"
        - "RID"
        - "NAME"
        - "PRICE"
        - "COST"
        - "LAST_UPDATED"
        timeOffset:
    Load_Orders_Data:
      type: "table-input"
      parameters:
        componentName: "Load_Orders_Data"
        database: "[Environment Default]"
        schema: "MAT_PRO"
        targetTable: "GW_ORDERS"
        columnNames:
        - "RowId"
        - "RID"
        - "CUSTOMER_RID"
        - "ORDER_DATE"
        - "LAST_UPDATED"
        timeOffset:
    Load_Order_Items_Data:
      type: "table-input"
      parameters:
        componentName: "Load_Order_Items_Data"
        database: "[Environment Default]"
        schema: "MAT_PRO"
        targetTable: "GW_ORDER_ITEMS"
        columnNames:
        - "RowId"
        - "RID"
        - "ORDER_RID"
        - "ITEM_RID"
        - "QUANTITY"
        - "LAST_UPDATED"
        timeOffset:
    Convert_Orders_Types:
      type: "convert-type"
      sources:
      - "Load_Orders_Data"
      parameters:
        componentName: "Convert_Orders_Types"
        conversions:
        - - "CUSTOMER_RID"
          - "NUMBER"
          - ""
          - ""
        - - "RID"
          - "NUMBER"
          - ""
          - ""
        - - "ORDER_DATE"
          - "DATE"
          - ""
          - ""
    Convert_Items_Types:
      type: "convert-type"
      sources:
      - "Load_Items_Data"
      parameters:
        componentName: "Convert_Items_Types"
        conversions:
        - - "RID"
          - "NUMBER"
          - ""
          - ""
        - - "COST"
          - "NUMBER"
          - ""
          - ""
        - - "PRICE"
          - "NUMBER"
          - ""
          - ""
    Convert_Order_Items_Types:
      type: "convert-type"
      sources:
      - "Load_Order_Items_Data"
      parameters:
        componentName: "Convert_Order_Items_Types"
        conversions:
        - - "ITEM_RID"
          - "NUMBER"
          - ""
          - ""
        - - "ORDER_RID"
          - "NUMBER"
          - ""
          - ""
        - - "RID"
          - "NUMBER"
          - ""
          - ""
        - - "QUANTITY"
          - "NUMBER"
          - ""
          - ""
    Join_All_Sales_Data:
      type: "join"
      sources:
      - "Extract_Customer_Details"
      - "Convert_Orders_Types"
      - "Convert_Items_Types"
      - "Convert_Order_Items_Types"
      parameters:
        componentName: "Join_All_Sales_Data"
        mainTable: "Convert_Order_Items_Types"
        mainTableAlias: "OI"
        joins:
        - - "Convert_Orders_Types"
          - "O"
          - "Inner"
        - - "Convert_Items_Types"
          - "I"
          - "Inner"
        - - "Extract_Customer_Details"
          - "A"
          - "Inner"
        joinExpressions:
        - - "\"OI\".\"ORDER_RID\"=\"O\".\"RID\""
          - "OI_Inner_O"
        - - "\"OI\".\"ITEM_RID\"=\"I\".\"RID\""
          - "OI_Inner_I"
        - - "\"O\".\"CUSTOMER_RID\"=\"A\".\"customer_rid\""
          - "OI_Inner_A"
        columnMappings:
        - - "O.ORDER_DATE"
          - "ORDER_DATE"
        - - "OI.QUANTITY"
          - "QUANTITY"
        - - "I.NAME"
          - "ITEM_NAME"
        - - "I.COST"
          - "COST"
        - - "I.PRICE"
          - "PRICE"
        - - "A.account_name"
          - "ACCOUNT_NAME"
    Calculate_Business_Metrics:
      type: "calculator"
      sources:
      - "Join_All_Sales_Data"
      parameters:
        componentName: "Calculate_Business_Metrics"
        includeInputColumns: "Yes"
        calculations:
        - - "(\"PRICE\"-\"COST\")*\"QUANTITY\""
          - "PROFIT"
        - - "(\"PRICE\" * \"QUANTITY\")"
          - "REVENUE"
        - - "TRUNCATE(\"ORDER_DATE\", 'mm')"
          - "ORDER_MONTH"
    Summarize_Sales_by_Account:
      type: "aggregate"
      sources:
      - "Calculate_Business_Metrics"
      parameters:
        componentName: "Summarize_Sales_by_Account"
        groupings:
        - "ITEM_NAME"
        - "ACCOUNT_NAME"
        - "ORDER_MONTH"
        aggregations:
        - - "PROFIT"
          - "Sum"
        - - "REVENUE"
          - "Sum"
        groupingType: "Group By"
    Save_Results_to_Table:
      type: "rewrite-table"
      sources:
      - "Summarize_Sales_by_Account"
      parameters:
        componentName: "Save_Results_to_Table"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "MAT_PRO"
        targetTable: "GW_PROFIT_BY_ACCOUNT"
        orderBy:
        - - "ORDER_MONTH"
          - "ASCENDING"
      postProcessing:
        updateOutputMessage: "${sysvar.thisComponent.rowCount}"
        updateScalarVariables:
design:
  components:
    Load_Customer_Data:
      position:
        x: 0
        "y": 0
      tempMetlId: 1
    Extract_Customer_Details:
      position:
        x: 200
        "y": 0
      tempMetlId: 2
    Load_Items_Data:
      position:
        x: 0
        "y": 100
      tempMetlId: 3
    Load_Orders_Data:
      position:
        x: 0
        "y": 200
      tempMetlId: 4
    Load_Order_Items_Data:
      position:
        x: 0
        "y": 300
      tempMetlId: 5
    Convert_Orders_Types:
      position:
        x: 200
        "y": 200
      tempMetlId: 6
    Convert_Items_Types:
      position:
        x: 200
        "y": 100
      tempMetlId: 7
    Convert_Order_Items_Types:
      position:
        x: 200
        "y": 300
      tempMetlId: 8
    Join_All_Sales_Data:
      position:
        x: 400
        "y": 150
      tempMetlId: 9
    Calculate_Business_Metrics:
      position:
        x: 600
        "y": 150
      tempMetlId: 10
    Summarize_Sales_by_Account:
      position:
        x: 800
        "y": 150
      tempMetlId: 11
    Save_Results_to_Table:
      position:
        x: 1000
        "y": 150
      tempMetlId: 12
